server.port=8083

spring.datasource.url=jdbc:mysql://localhost:3306/clos_application
spring.datasource.username=root
spring.datasource.password=MySQL@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

#--------enable circuitbreaker for feign client--------
#Whenever I make a Feign call, allow Spring Cloud Circuit Breaker to protect that call.
spring.cloud.openfeign.circuitbreaker.enabled=true 

#--------Feign timeout for customer_service--------
#When account-service tries to establish a connection with customer-service, don't wait longer than 1 second.
spring.cloud.openfeign.client.config.customer-service.connectTimeout=1000
#If customer-service doesn't return a response within the configured read timeout, the Feign call can time out.
spring.cloud.openfeign.client.config.customer-service.readTimeout=2000

#--------Circuit breaker resilience4j configuration-------
#Measure failures based on the number of requests
resilience4j.circuitbreaker.instances.customer-service.slidingWindowType=COUNT_BASED
#Look at the last 10 calls when calculating the failure rate
resilience4j.circuitbreaker.instances.customer-service.slidingWindowSize=10
#Don't make a circuit-breaker decision until at least 5 calls have happened
resilience4j.circuitbreaker.instances.customer-service.minimumNumberOfCalls=5
#If the failure rate reaches 50% or more, open the circuit
resilience4j.circuitbreaker.instances.customer-service.failureRateThreshold=50
#Once the circuit opens, keep it open for 10 seconds before allowing a recovery test
resilience4j.circuitbreaker.instances.customer-service.waitDurationInOpenState=10s
#After the 10-second wait, Resilience4j wants to find out: Has customer-service recovered? It changes to: HALF_OPEN Then it allows 3 test calls 
#If those test calls indicate the service has recovered, the circuit can close again.
#If the failures continue, the circuit can return to OPEN.
resilience4j.circuitbreaker.instances.customer-service.permittedNumberOfCallsInHalfOpenState=3

# Expose Actuator endpoints
management.endpoints.web.exposure.include=health,prometheus

# Enable Prometheus endpoint
management.endpoint.prometheus.enabled=true