server.port=8084

# =========================
# Gateway Routes
# =========================

#auth-service
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/auth/**

# customer service
spring.cloud.gateway.routes[1].id=customer-service
spring.cloud.gateway.routes[1].uri=lb://customer-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/customers/**

#Account service
spring.cloud.gateway.routes[2].id=account-service
spring.cloud.gateway.routes[2].uri=lb://account-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/account/**

# kyc service
spring.cloud.gateway.routes[3].id=kyc-service
spring.cloud.gateway.routes[3].uri=lb://kyc-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/kyc/**

eureka.client.service-url.defaultZone=http://localhost:8761/eureka